on:
  pull_request:
  merge_group:

run-name: Build and Lint

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Install bevy deps
        run: |
          sudo apt update -y
          sudo apt install -y pkg-config libxkbcommon-dev libwayland-dev libasound2-dev libudev-dev
      - run: |
          cargo fmt --check
          cargo clippy --all-targets --all-features
          cargo build --all-targets --all-features
